name: transpeach
description: "Projeto da disciplina de Multimídia"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9
  get: ^4.6.6
  cupertino_icons: ^1.0.6
  audioplayers: ^6.1.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  permission_handler: ^10.2.0
  path_provider: ^2.1.4
  flutter_sound: ^9.16.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
