# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: caiob
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: api-tts
# "service" is the name of this project. This will also be added to your AWS resource names.
service: api-tts

provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "polly:SynthesizeSpeech"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::ttsbucket111/*"
    - Effect: "Allow"
      Action:
        - "translate:TranslateText"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "transcribe:*"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::ttsbucket111/*"
        - "arn:aws:transcribe:us-east-1:*:transcription-job/*"
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  convertPolly:
    handler: handler.convertPolly
    events:
      - httpApi:
          path: /converter
          method: post
  translate:
    handler: handler.translate
    events:
      - httpApi:
          path: /translate
          method: post
